# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: counter.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\x12\x07\x63ounter\"N\n\x10IncrementRequest\x12\x12\n\ncounter_id\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x03\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\":\n\x0eIncrementReply\x12\x11\n\tnew_value\x18\x01 \x01(\x03\x12\x15\n\rwas_duplicate\x18\x02 \x01(\x08\" \n\nGetRequest\x12\x12\n\ncounter_id\x18\x01 \x01(\t\"(\n\x08GetReply\x12\r\n\x05value\x18\x01 \x01(\x03\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x32y\n\x07\x43ounter\x12?\n\tIncrement\x12\x19.counter.IncrementRequest\x1a\x17.counter.IncrementReply\x12-\n\x03Get\x12\x13.counter.GetRequest\x1a\x11.counter.GetReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'counter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INCREMENTREQUEST']._serialized_start=26
  _globals['_INCREMENTREQUEST']._serialized_end=104
  _globals['_INCREMENTREPLY']._serialized_start=106
  _globals['_INCREMENTREPLY']._serialized_end=164
  _globals['_GETREQUEST']._serialized_start=166
  _globals['_GETREQUEST']._serialized_end=198
  _globals['_GETREPLY']._serialized_start=200
  _globals['_GETREPLY']._serialized_end=240
  _globals['_COUNTER']._serialized_start=242
  _globals['_COUNTER']._serialized_end=363
# @@protoc_insertion_point(module_scope)
